# Generated by Django 4.0.1 on 2022-04-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_alter_destination1_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination1',
            name='Password',
            field=models.IntegerField(default=0, verbose_name=1000),
            preserve_default=False,
        ),
    ]
